### ISSUE TITLE
runner: workflow `outputs` shape is validated only after every step has run

### ISSUE THREAD

**Issue by char0n** [usearazzo/arazzo-toolkit#53]
## Problem

A workflow whose `outputs` is present but not a map is only detected once the run is over — after every step has made its live requests.

```yaml
- workflowId: lateOutputs
  steps: [{ stepId: only, operationId: getInventory }]
  outputs: not-a-map
```

```
lateOutputs -> ResolverError malformed-outputs; HTTP calls BEFORE throw = 1
```

`OutputResolver` is reached for workflow outputs from `WorkflowExecutor.#result`, i.e. at the very end. The document was unrunnable from the start, but the runner discovers it only after the side effects have happened.

## Why it matters

The executor already takes the opposite position elsewhere, deliberately. `#orderedSteps` validates a malformed `steps` **before any prerequisite runs**, with the reasoning stated inline:

> validated before any prerequisite runs: a malformed `steps` is an authoring error, and discovering it only after the dependencies have fired would mean live side effects on the way to a throw.

A malformed `outputs` is the same kind of authoring error and deserves the same treatment. As it stands, a workflow that cannot possibly produce its outputs still performs every write it was going to perform.

## Proposed change

A pre-flight shape check on `workflow.outputs` alongside the existing `#orderedSteps` validation, so the run fails before the first request rather than after the last.

Worth deciding at the same time whether step-level `outputs` deserves the same (it is resolved per step, so the blast radius is one step rather than a whole run — a weaker case).

## Not introduced by #51

Pre-existing, and not a regression: before #51 this crashed with `TypeError: outputs.forEach is not a function` at exactly the same late point. #51 made it a typed error; it did not move it.
